### PR TITLE
Small improvements after checking code with Perl::Critic and Perl::Minim...

### PR DESCRIPTION
**Pull request by somerandomlogin**
...umVersion.

- Changed the required version to 5.6 from 5.4 after checking with Perl::MinimumVersion:
"use warnings" pragma was introduced in Perl 5.6.

- Replaced "use vars" with "our" variables. Quote from "vars" pragma documentation:
"the functionality provided by this pragma has been superseded by our declarations, available in Perl v5.6.0 or later, and use of this pragma is discouraged."

- Removed a rogue comma. Perl::Critic message:
"Comma used to separate statements at line 29, column 5.  See pages 68,71 of PBP.  (Severity: 4)"

### CODE REVIEW

**Comment by somerandomlogin** [comment]
Hi.

Here are the changes I've made for now.
There are some more things to improve, but we'd need to discuss them first.

Thanks.

**Comment by somerandomlogin** [comment]
Okay, so there's a couple more of Perl::Critic messages:

1. `@ISA used instead of "use base" at line 10, column 5.  See page 360 of PBP.  (Severity: 3)`
Apparently messing with `@ISA` in runtime is considered to be a bad practice and `use base` should be used instead -- but that will bump the minimum required version to 5.6.

2. `Symbols are exported by default at line 12, column 1.  Use '@EXPORT_OK' or '%EXPORT_TAGS' instead.  (Severity: 4)`
`truncstr` subroutine is exported by default, which isn't considered to be a good practice either. I could fix that, but it might break any existing code that uses Text::Truncate. I'm not sure if that's a concern or not.

So, tell me what you think -- I can fix those things too if you are okay with that.

Thanks.

**Comment by ilv** [comment]
Hi!

Thanks for the improvements. I've created a develop branch, could you please make a pull request to that branch instead of master?

About the last points, for now I would say let's go just with 1)

**Comment by somerandomlogin** [comment]
I've created a pull request and will make changes for item 1, too.

**Pull request closed without merging**
