### PR TITLE
SEE ALSO As hyper link

### PR DESCRIPTION
**Pull request by plicease**
The links in the SEE ALSO section are indented by one space which means they are rendered as literal text and you cannot click on them, rendering the L<..> markup ineffective.  This patch removes the indent so they can become links.  Also update the link to the repository.

### CODE REVIEW

**Comment by plicease** [comment]
sorry, that should have gone against your develop branch!

**Comment by ilv** [comment]
Hello there. I'll review this during the weekend. Thanks!

**Comment by ilv** [comment]
@plicease Hi, thanks for the contribution. Could you please open a new pull request, this time for the develop branch? Also, I noticed the link to the repo still points out to my old GitHub account (ileiva). It would be great if you could change that too!

**Comment by plicease** [comment]
no problem.

**Pull request closed without merging**
